sudo: required

language: generic

services:
  - docker

before_script:
  - echo "start creating an image with dockerfile"
  - docker build -t myp7166/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true myp7166/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-186444673342"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
